provider "bsky" {
  pds_host           = "https://bsky.social"
  handle             = "scoott.blog"
  pds_admin_password = "<PDS admin password>"
}

resource "bsky_account" "test-account" {
  email  = "test@scoott.blog"
  handle = "test.scoott.blog"
  // if account password is not specified when creating a new user, one will be autogenerated
}


// example using a bsky_account to create a Cloudflare DNS TXT record with the DID to validate the handle
provider "cloudflare" {
  api_token = "<cloudflare api token>"
}

resource "cloudflare_dns_record" "test-account-dns-verify" {
  zone_id = "<cloudflare zone id>"
  name    = "_atproto.${element(split(".", bsky_account.test-account.handle), 0)}"
  content = "\"did=${bsky_account.test-account.did}\""
  comment = "Bluesky handle verification record for ${bsky_account.test-account.handle}"
  ttl     = 1 // auto
  type    = "TXT"
}